name: Check iOS App

on:
  push:
    paths:
      - 'ios/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: build app
        working-directory: 'ios'
        run: |
          xcodebuild -scheme YATA -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

      - name: run tests
        working-directory: 'ios'
        run: |
          xcodebuild clean test -scheme YATA -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

  swift-lint:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true
          working-directory: 'ios'

      - name: setup swiftlint
        run: |
          brew install swiftlint

      - name: run swift lint
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'swift_lint'
          subdirectory: 'ios'
